---

- name: Add JRE ppa
  apt_repository: repo=ppa:webupd8team/java state=present

- name: Copy configuration file for dns
  template: src={{ item }}.j2 dest=/etc/{{ item }}
  with_items:
    - resolv.conf

- name: Write empty iterfaces
  shell: sudo nano interfaces

- name: Copy configuration file for network interface
  template: src={{ item }}.j2 dest=/etc/networkd/{{ item }}
  with_items:
    - interfaces

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Get JRE
  shell: wget "http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-7u80-linux-x64.tar.gz"

- name: Move JRE
  shell: sudo mv jdk-7u80-linux-x64.tar.gz /tmp/

- name: Local Path 
  shell: echo oracle-java7-installer oracle-java7-installer/local select /tmp | sudo /usr/bin/debconf-set-selections

- name: Approve
  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install JRE
  apt: name=oracle-java7-installer update_cache=yes state=latest
 
# Check if apache2 is already installed
- name: Detect existing Apache installation at /etc/apache2$
  stat: path=/etc/apache2$
  register: state_of_apache2_installation

# Check if tomcat8 is already installed
- name: Detect existing tomcat8 installation at /etc/tomcat8$
  stat: path=/etc/tomcat8$
  register: state_of_tomcat8_installation

- name: Install apache2
  apt: name=apache2 update_cache=yes state=latest

- name: Start tomcat
  service: name=tomcat8 state=started

- name: Install tomcat8
  apt: name=tomcat8 update_cache=yes state=latest

